### ISSUE TITLE
"error: redefinition of 'main'" during compilation of demo/hello

### ISSUE THREAD

**Issue by xushangning** [faasm/faasm#353]
Faasm version: master (0f4460fabe8a6f8b354f83fb752740100d653d64)

Try to follow the quick start in README using the container development environment and encounter the following errors during `inv compile demo hello`:

```
FAILED: demo/CMakeFiles/hello.dir/hello.cpp.obj 
/usr/local/faasm/toolchain/bin/clang++ --target=wasm32-wasi --sysroot=/usr/local/faasm/llvm-sysroot -DWASM_PROF=1 -D__faasm  -O3 -mno-atomics     --sysroot=/usr/local/faasm/llvm-sysroot     -m32     -DANSI     -Xlinker --stack-first      -O3 -DNDEBUG -std=gnu++17 -MD -MT demo/CMakeFiles/hello.dir/hello.cpp.obj -MF demo/CMakeFiles/hello.dir/hello.cpp.obj.d -o demo/CMakeFiles/hello.dir/hello.cpp.obj -c /usr/local/code/faasm/func/demo/hello.cpp
clang-10: warning: -Xlinker --stack-first: 'linker' input unused [-Wunused-command-line-argument]
/usr/local/code/faasm/func/demo/hello.cpp:3:5: error: redefinition of 'main'
int main(int argc, char* argv[])
    ^
/usr/local/faasm/llvm-sysroot/include/faasm/faasm.h:10:5: note: previous definition is here
int main(int argc, char *argv[]) {
    ^
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.8/dist-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.8/dist-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.8/dist-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/code/faasm/faasmcli/faasmcli/tasks/compile.py", line 32, in compile
    wasm_cmake(FUNC_DIR, FUNC_BUILD_DIR, target, clean, debug, sgx=sgx)
  File "/usr/local/code/faasm/faasmcli/faasmcli/util/compile.py", line 42, in wasm_cmake
    raise RuntimeError("failed on make for {}".format(target))
RuntimeError: failed on make for hello
```

Another definition of `main` is in the file `/usr/local/faasm/llvm-sysroot/include/faasm/faasm.h`, shown below:

```cpp
#ifndef _FAASM_H
#define _FAASM_H

#include "faasm/core.h"

// Hooks for handling normal argc/argv
int faasm_argc;
char** faasm_argv;

int main(int argc, char *argv[]) {
    faasm_argc = argc;
    faasm_argv = argv;

    int idx = faasmGetCurrentIdx();
    return exec(idx);
}

#endif
```

It does seem to be a redefinition in my opinion. Can I just remove `main` in `faasm.h`?

**Comment by Shillaker** [comment]
Hi @xushangning , sorry for the slow reply, we've been busy working on some other changes to the project. I imagine you've given up on this now, but I'll fix it today anyway. 

Thanks for raising.

**Comment by xushangning** [comment]
That's fine. I'm still keeping a tab on the project!

**Comment by xushangning** [comment]
Check out the master (0972ab9415a635bfd4cf131015a1a52179d04dd4) today and I was able to complete the quick start. Kudos!

**Comment by Shillaker** [comment]
Ah that's good news! I actually still need to do another push to fully fix the Python execution, so if you spot anything else then definitely raise another issue. 

We've been doing a lot of housework on the repos so stuff is moving around a lot. Should calm down soon :crossed_fingers:
