### ISSUE TITLE
inv dev.tools : ninja error: protobuf/3.20.0 missing and no known rule to make it

### ISSUE THREAD

**Issue by FlowDrucka64** [faasm/faasm#662]
Hello!
When running ``inv dev.rools`` withing the faasm cli (entered via ``./bin/cli.sh faasm``) the following happens:
```
cmake --build . --target codegen_func codegen_shared_obj func_runner func_sym pool_runner upload tests
ninja: error: '/root/.conan/data/protobuf/3.20.0/_/_/package/3f74f3dd13a486e4ca5686adb7b5f7441ee8f208/bin/protoc', needed by 'faabric/src/proto/faabric.pb.h', missing and no known rule to make it
Traceback (most recent call last):
  File "/usr/local/code/faasm/venv/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/code/faasm/faasmcli/faasmcli/tasks/dev.py", line 95, in tools
    run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --target codegen_func codegen_shared_obj func_runner func_sym pool_runner upload tests' returned non-zero exit status 1
```

**Comment by csegarragonz** [comment]
Hey!

Could you confirm you are running with the latest `main` commit?

Other than that, it could be that your installation has broken for some reason. The easiest solution in this case is to nuke your current working environment and re-build from scratch.

The soft approach is just running the same command with the `--clean` flag, that is (inside the container):

```bash
inv dev.tools --clean
```

If that does not work, you can try removing all the conan-installed dependencies forcing the system to re-download and install them (could take a while). In the process, you can also manually remove all your build files. From inside the container do:

```bash
rm -r /root/.conan/*
rm -r /build/faasm/*

inv dev.tools --clean
```

Let me know if this fixes your issue.

**Comment by FlowDrucka64** [comment]
Thank you for your fast response!
I am running the latest main commit.
Running ``inv dev.tools --clean`` fixed the problem.
