### ISSUE TITLE
ERROR: fmt/8.0.1: Cannot load recipe. / Error loading conanfile 

### ISSUE THREAD

**Issue by FlowDrucka64** [faasm/faasm#664]
Hello!
I've been working on the revival of TF and was making good progress.
After a one day break, when invoking dev.camke in the faasm container the following happens:

```
ERROR: fmt/8.0.1: Cannot load recipe.
Error loading conanfile at '/root/.conan/data/fmt/8.0.1/_/_/export/conanfile.py': Unable to load conanfile in /root/.conan/data/fmt/8.0.1/_/_/export/conanfile.py
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.conan/data/fmt/8.0.1/_/_/export/conanfile.py", line 5, in <module>
    from conan.tools.scm import Version
ModuleNotFoundError: No module named 'conan.tools.scm'

CMake Error at /build/faasm/faabric/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  faabric/cmake/ExternalProjects.cmake:71 (conan_cmake_install)
  faabric/CMakeLists.txt:65 (include)


-- Configuring incomplete, errors occurred!
See also "/build/faasm/CMakeFiles/CMakeOutput.log".
See also "/build/faasm/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/usr/local/code/faasm/venv/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/code/faasm/venv/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/code/faasm/faasmcli/faasmcli/tasks/dev.py", line 69, in cmake
    run(cmd_str, shell=True, check=True, cwd=FAASM_BUILD_DIR)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++-13 -DCMAKE_C_COMPILER=/usr/bin/clang-13 -DCMAKE_INSTALL_PREFIX=/usr/local    -DFAASM_USE_SANITISER=None -DFAABRIC_USE_SANITISER=None -DFAASM_SGX_MODE=Disabled  /usr/local/code/faasm' returned non-zero exit status 1.
```

Is this error occuring because I broke something?
(I already nuked everything (faasm repo, docker containers & volumes) but the docker images)

**Comment by FlowDrucka64** [comment]
Error log:
```
(faasm) root@7aa3bdfe90d1:/usr/local/code/faasm# cat /build/faasm/CMakeFiles/CMakeError.log
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /build/faasm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_b3aa5 && [1/2] Building C object CMakeFiles/cmTC_b3aa5.dir/src.c.o
[2/2] Linking C executable cmTC_b3aa5
FAILED: cmTC_b3aa5
: && /usr/bin/clang-13  -fuse-ld=lld CMakeFiles/cmTC_b3aa5.dir/src.c.o -o cmTC_b3aa5   && :
ld.lld: error: undefined symbol: pthread_create
>>> referenced by src.c
>>>               CMakeFiles/cmTC_b3aa5.dir/src.c.o:(main)

ld.lld: error: undefined symbol: pthread_detach
>>> referenced by src.c
>>>               CMakeFiles/cmTC_b3aa5.dir/src.c.o:(main)

ld.lld: error: undefined symbol: pthread_cancel
>>> referenced by src.c
>>>               CMakeFiles/cmTC_b3aa5.dir/src.c.o:(main)

ld.lld: error: undefined symbol: pthread_join
>>> referenced by src.c
>>>               CMakeFiles/cmTC_b3aa5.dir/src.c.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /build/faasm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_b6db9 && [1/2] Building C object CMakeFiles/cmTC_b6db9.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_b6db9
FAILED: cmTC_b6db9
: && /usr/bin/clang-13 -DCHECK_FUNCTION_EXISTS=pthread_create -fuse-ld=lld CMakeFiles/cmTC_b6db9.dir/CheckFunctionExists.c.o -o cmTC_b6db9  -lpthreads && :
ld.lld: error: unable to find library -lpthreads
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.



Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
Ubuntu clang version 13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Performing C++ SOURCE FILE Test CXX_HAS_WDUPLICATED_COND failed with the following output:
Change Dir: /build/faasm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_311e3 && [1/2] Building CXX object CMakeFiles/cmTC_311e3.dir/src.cxx.o
warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]
1 warning generated.
[2/2] Linking CXX executable cmTC_311e3


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test CXX_HAS_WDUPLICATED_BRANCHES failed with the following output:
Change Dir: /build/faasm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_72ac8 && [1/2] Building CXX object CMakeFiles/cmTC_72ac8.dir/src.cxx.o
warning: unknown warning option '-Wduplicated-branches' [-Wunknown-warning-option]
1 warning generated.
[2/2] Linking CXX executable cmTC_72ac8


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test CXX_HAS_WLOGICAL_OP failed with the following output:
Change Dir: /build/faasm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_0f0b5 && [1/2] Building CXX object CMakeFiles/cmTC_0f0b5.dir/src.cxx.o
warning: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Wunknown-warning-option]
1 warning generated.
[2/2] Linking CXX executable cmTC_0f0b5


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test CXX_HAS_WRESTRICT failed with the following output:
Change Dir: /build/faasm/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja cmTC_831b1 && [1/2] Building CXX object CMakeFiles/cmTC_831b1.dir/src.cxx.o
warning: unknown warning option '-Wrestrict' [-Wunknown-warning-option]
1 warning generated.
[2/2] Linking CXX executable cmTC_831b1


Source file was:
int main() { return 0; }
```

**Comment by Shillaker** [comment]
Hi @FlowDrucka64, with anything related to Conan the first step is to try to upgrade Conan itself. This seems to work in my case. Can you run the following in your Faasm `cli` container?

```
curl -s -L -o /tmp/conan-latest.deb https://github.com/conan-io/conan/releases/download/1.51.0/conan-ubuntu-64.deb && sudo dpkg -i /tmp/conan-latest.deb && rm -f /tmp/conan-latest.deb
```

Then retry?

**Comment by FlowDrucka64** [comment]
Thanks for your reply!
Updating conan fixed it. Kinda feel stupid for not comming up with that myself.
