### ISSUE TITLE
TypeError with faasmctl compose

### ISSUE THREAD

**Issue by kaimast** [faasm/faasm#793]
When running `faasmcli compose.compose` I get the following output:

```
 Network faasm-576121_default  Creating
 Network faasm-576121_default  Created
 Volume "faasm-576121_aesmd-socket"  Creating
 Volume "faasm-576121_aesmd-socket"  Created
 Container faasm-576121-redis-queue-1  Creating
 Container faasm-576121-minio-1  Creating
 Container faasm-576121-planner-1  Creating
 Container faasm-576121-redis-state-1  Creating
 Container faasm-576121-planner-1  Created
 Container faasm-576121-redis-queue-1  Created
 Container faasm-576121-minio-1  Created
 Container faasm-576121-redis-state-1  Created
 Container faasm-576121-upload-1  Creating
 Container faasm-576121-upload-1  Created
 Container faasm-576121-worker-2  Creating
 Container faasm-576121-worker-1  Creating
 Container faasm-576121-worker-2  Created
 Container faasm-576121-worker-1  Created
 Container faasm-576121-minio-1  Starting
 Container faasm-576121-redis-state-1  Starting
 Container faasm-576121-planner-1  Starting
 Container faasm-576121-redis-queue-1  Starting
 Container faasm-576121-redis-state-1  Started
 Container faasm-576121-minio-1  Started
 Container faasm-576121-planner-1  Started
 Container faasm-576121-redis-queue-1  Started
 Container faasm-576121-upload-1  Starting
 Container faasm-576121-upload-1  Started
 Container faasm-576121-worker-2  Starting
 Container faasm-576121-worker-2  Started
 Container faasm-576121-worker-1  Starting
 Container faasm-576121-worker-1  Started
Traceback (most recent call last):
  File "/home/kai/dev/research/faasm/venv-bm/bin/faasmctl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/faasmctl/main.py", line 14, in main
    program.run()
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/faasmctl/tasks/deploy.py", line 50, in compose
    return deploy_compose_cluster(faasm_checkout, workers, mount_source, ini_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/faasmctl/util/compose.py", line 143, in deploy_compose_cluster
    worker_names=get_container_names_from_compose(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/faasmctl/util/compose.py", line 324, in get_container_names_from_compose
    return [c["Name"] for c in json_array if c["Service"] == "worker"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/dev/research/faasm/venv-bm/lib/python3.11/site-packages/faasmctl/util/compose.py", line 324, in <listcomp>
    return [c["Name"] for c in json_array if c["Service"] == "worker"]
                                             ~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

`json_array` seems to be a double-nested array for me, not sure why. Its content looked like this for me:
```python
[[{'ID': '1d2a33bc3b4068f2b7f108dfc40d19859f9eb94613b33ea61c664ea622205b62', 'Name': 'faasm-576121-minio-1', 'Image': 'faasm.azurecr.io/minio:0.12.0', 'Command': '/usr/bin/docker-entrypoint.sh server /data/minio', 'Project': 'faasm-576121', 'Service': 'minio', 'Created': 1694974791, 'State': 'running', 'Status': 'Up 1 second (health: starting)', 'Health': 'starting', 'ExitCode': 0, 'Publishers': [{'URL': '0.0.0.0', 'TargetPort': 9000, 'PublishedPort': 9000, 'Protocol': 'tcp'}, {'URL': '::', 'TargetPort': 9000, 'PublishedPort': 9000, 'Protocol': 'tcp'}]}, {'ID': '7c6418ff8e71e575494149c720ad79bbf09ab1168a8055a1e04cf54fe7f1c58f', 'Name': 'faasm-576121-planner-1', 'Image': 'faasm.azurecr.io/planner:0.8.0', 'Command': '/code/faabric/bin/planner_entrypoint.sh /build/faabric/static/bin', 'Project': 'faasm-576121', 'Service': 'planner', 'Created': 1694974791, 'State': 'running', 'Status': 'Up 1 second', 'Health': '', 'ExitCode': 0, 'Publishers': [{'URL': '0.0.0.0', 'TargetPort': 8080, 'PublishedPort': 8080, 'Protocol': 'tcp'}, {'URL': '::', 'TargetPort': 8080, 'PublishedPort': 8080, 'Protocol': 'tcp'}]}, {'ID': '1d9823f4d86d4545e95141593bea542135d814deb8a5a988add1385e37a70f02', 'Name': 'faasm-576121-redis-queue-1', 'Image': 'faasm.azurecr.io/redis:0.12.0', 'Command': 'docker-entrypoint.sh redis-server /redis.conf', 'Project': 'faasm-576121', 'Service': 'redis-queue', 'Created': 1694974791, 'State': 'running', 'Status': 'Up Less than a second', 'Health': '', 'ExitCode': 0, 'Publishers': [{'URL': '', 'TargetPort': 6379, 'PublishedPort': 0, 'Protocol': 'tcp'}]}, {'ID': '8c7d75a855d45351c3f2efa62f6dabb95e07ee94f0b0d5ff4eddab60d621ac2c', 'Name': 'faasm-576121-redis-state-1', 'Image': 'faasm.azurecr.io/redis:0.12.0', 'Command': 'docker-entrypoint.sh redis-server /redis.conf', 'Project': 'faasm-576121', 'Service': 'redis-state', 'Created': 1694974791, 'State': 'running', 'Status': 'Up 1 second', 'Health': '', 'ExitCode': 0, 'Publishers': [{'URL': '', 'TargetPort': 6379, 'PublishedPort': 0, 'Protocol': 'tcp'}]}, {'ID': '8fb9d6c16819d8b6e523b5d04f654785ba1f20164cb10e7eff0a4138f52368e0', 'Name': 'faasm-576121-upload-1', 'Image': 'faasm.azurecr.io/upload:0.12.0', 'Command': '/entrypoint.sh /bin/bash -c "/build/faasm/bin/upload"', 'Project': 'faasm-576121', 'Service': 'upload', 'Created': 1694974792, 'State': 'running', 'Status': 'Up Less than a second (health: starting)', 'Health': 'starting', 'ExitCode': 0, 'Publishers': [{'URL': '', 'TargetPort': 5000, 'PublishedPort': 0, 'Protocol': 'tcp'}, {'URL': '0.0.0.0', 'TargetPort': 8002, 'PublishedPort': 8002, 'Protocol': 'tcp'}, {'URL': '::', 'TargetPort': 8002, 'PublishedPort': 8002, 'Protocol': 'tcp'}]}, {'ID': '08b9df0bb97e0f85a6657a36b83c87d5fe5177d16e9de530c383aaa40d424c31', 'Name': 'faasm-576121-worker-1', 'Image': 'faasm.azurecr.io/worker:0.12.0', 'Command': '/entrypoint.sh /bin/bash -c "/build/faasm/bin/pool_runner"', 'Project': 'faasm-576121', 'Service': 'worker', 'Created': 1694974792, 'State': 'running', 'Status': 'Up Less than a second', 'Health': '', 'ExitCode': 0, 'Publishers': [{'URL': '', 'TargetPort': 5000, 'PublishedPort': 0, 'Protocol': 'tcp'}]}, {'ID': '32280fc7fafdd71078098a3ae3e263205ac4de677476c44718fc8d52d1cfa114', 'Name': 'faasm-576121-worker-2', 'Image': 'faasm.azurecr.io/worker:0.12.0', 'Command': '/entrypoint.sh /bin/bash -c "/build/faasm/bin/pool_runner"', 'Project': 'faasm-576121', 'Service': 'worker', 'Created': 1694974792, 'State': 'running', 'Status': 'Up Less than a second', 'Health': '', 'ExitCode': 0, 'Publishers': [{'URL': '', 'TargetPort': 5000, 'PublishedPort': 0, 'Protocol': 'tcp'}]}]]
```

So I added the `[0]` below to make faasmctl work as expected.
```python
json_array = [json_loads(json_str)[0] for json_str in json_str_array]
return [c["Name"] for c in json_array if c["Service"] == "worker"]
```

Unrelated: I also had to set  `export FAASM_INI_FILE=./faasm.ini` afterwards to make calls to faasmctl work properly. Not sure if this is supposed to be set by the compose command? Maybe faasmctl should look for faasm.ini in the working directory if the variable is not set?

**Comment by csegarragonz** [comment]
Hey @kaimast thanks for reporting this!

What version of `docker compose` are you using locally? (`docker compose version`).

Unfortunately, `docker compose` introduced a breaking change as part of their `2.21.0` release ([see notes here](https://github.com/docker/compose/releases/tag/v2.21.0)).

I had to upgrade `faasmctl` as GitHub's Action runners were using the latest `docker compose`, which was breaking our integration tests in the exact same way you describe. The relevant PR is faasm/faasmctl#48.

Please, try to upgrade `docker compose` locally, and let me know if the error persists.

Regarding the `FAASM_INI_FILE` variable exporting you are right. This is also the expected behavior to support having concurrent Faasm clusters both locally, and remotely.

**Comment by kaimast** [comment]
Updating docker-compose fixes it!
