### ISSUE TITLE
faasm chain examples not progressing

### ISSUE THREAD

**Issue by JefferyLim** [faasm/faasm#795]
I am attempting to run the chain demos from https://github.com/faasm/cpp. 

I attempted to run the following commands:

```
faasmctl cli.cpp

inv func demo chain

inv func.upload demo chain

inv func.invoke demo chain
```

And it does not seem to make any progress.

**Comment by csegarragonz** [comment]
Hi @JefferyLim thanks for reporting this and for using Faasm!

From the logs, it does indeed look like Faasm is working as expected. My gut feeling is that the problem is then with [`faasmctl`](https://github.com/faasm/faasmctl), the CLI tool we use to interact with running Faasm clusters. The tool is fairly new, so I except there to be some issues 🙈 

One of the fiddly details is that the CPP container (`faasmctl cli.cpp`) that we use to cross-compile C++ code to WASM tracks its [own version](https://github.com/faasm/cpp/blob/main/requirements.txt#L2) of `faasmctl` (that we bake into the container) so it could be out of date. In order to debug it could you maybe do the following:

```bash
# Start a Faasm cluster using a development version of faasmctl
git clone https://github.com/faasm/faasmctl
cd faasmctl
source ./bin/workon.sh
inv deploy.compose --mount-source <path_to_your_faasm_checkout>

# Compile and upload (but NOT invoke) the chain function with the CPP container
faasmctl cli.cpp
inv func demo chain func.upload demo chain
exit

# Invoke from the development version of faasmctl
inv invoke demo chain
```

this way you will be able to see in which part of the python code `faasmctl` is getting stuck.

**Comment by JefferyLim** [comment]
faasmctl/bin/workon.sh expects a VERSION file, which seems to have been done away with. 

There also is no `inv deploy.compose` in the faasmctl virtual environment (unless I am suppose to run it in the faasm one)

**Comment by JefferyLim** [comment]
Ah, I believe the command is supposed to be `faasmctl deploy.compose`.

I am encountering another issue here:

`inv func demo chain func.upload demo chain`  returns:

```
(cpp) root@25c275bf893c:/code/cpp# inv func demo chain func.upload demo chain
cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/usr/local/faasm/toolchain/tools/WasiToolchain.cmake -DCMAKE_BUILD_TYPE=Release /code/cpp/func
-- Faasm building STATIC libraries
-- Faasm building target wasm32-wasi
System is unknown to cmake, create:
Platform/Wasm to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please post that file on discourse.cmake.org.
-- Detected wasm build (sysroot=/usr/local/faasm/llvm-sysroot)
-- Configuring done
-- Generating done
-- Build files have been written to: /code/cpp/build/func
ninja: no work to do.
Traceback (most recent call last):
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5c05a38370>: Failed to establish a new connection: [Errno 113] No route to host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/cpp/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/code/cpp/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='upload', port=8002): Max retries exceeded with url: /f/demo/chain (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c05a38370>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/cpp/venv/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/code/cpp/venv/lib/python3.10/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/code/cpp/venv/lib/python3.10/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/code/cpp/venv/lib/python3.10/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
  File "/code/cpp/venv/lib/python3.10/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
  File "/code/cpp/tasks/func.py", line 79, in upload
    upload_wasm(user, func, func_file)
  File "/code/cpp/venv/lib/python3.10/site-packages/faasmctl/util/upload.py", line 19, in upload_wasm
    response = put(url, data=open(wasm_file, "rb"))
  File "/code/cpp/venv/lib/python3.10/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "/code/cpp/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/code/cpp/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/code/cpp/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/code/cpp/venv/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='upload', port=8002): Max retries exceeded with url: /f/demo/chain (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c05a38370>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by csegarragonz** [comment]
Yes, apologies, you are right, I meant to say: `faasmctl deploy.compose --mount-source <path_to_checkout>`

And you are right re. the VERSION file, I need to update that.

You can see the logs for a service by running: `faasmctl logs -s upload`.

That being said, I presume the reason why it is not happy is because when `--mount-source`-ing, Faasm expects to find the compiled binaries for all services. You can do two things:

Run `faasmctl deply.compose` from your local `faasmctl` checkout (without `--mount-source`), this will use the tagged version of Faasm.

Alternatively, manually build the binaries in your local Faasm checkout:

```bash
# Start cluster mounting source and binaries
faasmctl deploy.compose --mount-source <faasm_checkout>
export FAASM_INI_FILE=./faasm.ini

# Build all binaries
faasmctl cli.faasm
inv dev.tools
exit

# Now restart the services that were failing
faasmctl restart -s upload -s worker
```

Hope this helps!

**Comment by JefferyLim** [comment]
I manually built the binaries in my local Faasm checkout, and it seems that the original issue is still occurring (calls to invoke a function that uses chains does not return).

I'm finding additional issues trying to run the pi example. My first invoke for pi returns the Pi estimate print. My second invoke for pi returns nothing. A third attempt gives me the estimate (and this pattern continues)

```
faasm-972842-worker-3       | [03:48:44] [144] [I] Chaining nested call demo/pi (ids: 423803 -> 1423855356)
faasm-972842-worker-3       | [03:48:44] [144] [I] Chaining nested call demo/pi (ids: 423803 -> 1423855360)
faasm-972842-worker-3       | [03:48:44] [144] [I] Chaining nested call demo/pi (ids: 423803 -> 1423855364)
faasm-972842-worker-3       | [03:48:44] [144] [I] Chaining nested call demo/pi (ids: 423803 -> 1423855367)
faasm-972842-worker-3       | piStep: 78366
faasm-972842-worker-7       | piStep: 78557
faasm-972842-worker-3       | piStep: 78598
faasm-972842-worker-3       | piStep: 78814
faasm-972842-worker-3       | Pi estimate: 3.144210(error 0.002620)
faasm-972842-planner-1      | [03:48:45] [40] [I] Planner removing app 689406 from in-flight
faasm-972842-worker-3       | [03:48:49] [144] [I] Chaining nested call demo/pi (ids: 739025 -> 1423855371)
faasm-972842-worker-3       | [03:48:49] [144] [I] Chaining nested call demo/pi (ids: 739025 -> 1423855374)
faasm-972842-worker-3       | [03:48:49] [144] [I] Chaining nested call demo/pi (ids: 739025 -> 1423855377)
faasm-972842-worker-3       | [03:48:49] [144] [I] Chaining nested call demo/pi (ids: 739025 -> 1423855380)
faasm-972842-worker-3       | piStep: 78448
faasm-972842-worker-3       | piStep: 78242
faasm-972842-worker-3       | piStep: 78352
faasm-972842-worker-7       | piStep: 78520
```

**Comment by csegarragonz** [comment]
Apologies if I didn't make myself very clear.

My hunch is that the error is in the result gathering Python scripts in `faasmctl` rather than in the Faasm runtime itself. That is why I encouraged you to use a development version of `faasmctl` to be able to debug further what the method is doing.

As I said, you just need to deploy the cluster (mounting the source wherever you want) from your local checkout of `faasmctl` (make sure to be in the virtual environment):

```bash
cd faasmctl
source ./bin/workon.sh
faasmctl deploy.compose --mount-source <path_to_faasm_checkout>
```

then you can see how `faasmctl invoke` works. My bet is that it is waiting for the wrong message ids.

To see what functions finish executing, I would also recommend enabling `debug` logs in the `planner` service:

```bash
faasmctl delete

# Mdodify faasm/docker-compose.yml in the planner to have `LOG_LEVEL=debug`

faasmctl deploy.compose --mount-source ...
faasmctl logs -s planner -f
```

you may do the same with the `worker` service  too.

**Comment by JefferyLim** [comment]
No, your explanation is clear! Sorry, I've been trying out some of the other demos. Here's an example of the logs output when doing it this way for demo/pi:

```
faasm-101769-worker-4   | Pi estimate: 3.140110(error 0.001480)
faasm-101769-planner-1  | [00:24:14] [41] [D] Planner setting message result (id: 978126) for 824612:2085523783:0
faasm-101769-planner-1  | [00:24:14] [41] [D] Removing message 978126 from app 824612
faasm-101769-planner-1  | [00:24:14] [41] [I] Planner removing app 824612 from in-flight
faasm-101769-planner-1  | [00:24:16] [52] [D] Faabric planner received request
faasm-101769-planner-1  | [00:24:16] [52] [D] Planner received EXECUTE_BATCH_STATUS request
faasm-101769-planner-1  | [00:24:18] [51] [D] Faabric planner received request
faasm-101769-planner-1  | [00:24:18] [51] [D] Planner received EXECUTE_BATCH_STATUS request
faasm-101769-planner-1  | [00:24:20] [51] [D] Faabric planner received request
```

The planner messages stops once I `ctrl+c` from the faasmctl invoke.

**Comment by HiranmayeeKadali** [comment]
Hey @csegarragonz @JefferyLim! Have you been able to solve the issue. Since I have a similar issue while invoking the uploaded function. I'm not able to progress further. Can you let me know how to resolve this please. 
![Screenshot from 2024-05-09 15-14-27](https://github.com/faasm/faasm/assets/167014484/fcd42597-ebcb-429c-801a-b3d20a140394)

**Comment by csegarragonz** [comment]
hey @HiranmayeeKadali this looks like a different issue.

@JefferyLim 's issue is a known issue when flushing the same function multiple times.
yours seems to be an issue when uploadin the cpython function (notice the 500 status code after `cpython.upload`)

python support is kinda broken as of now so i would not expect it to work (just yet!)

**Comment by HiranmayeeKadali** [comment]
Hey @JefferyLim I have the same error trying to invoke function in cpp though I get a response when I upload the function, it takes quite a lot of time to invoke it. Is there something that I'm missing?

**Comment by csegarragonz** [comment]
Could you provide more details about what it is that you are doing and what is the error that you are getting?

**Comment by HiranmayeeKadali** [comment]
Hii @JefferyLim I can invoke hello function but I cannot invoke other functions, though it uploads successfully. I'm deploying the faasm in a K8 cluster on GCP. I'm attaching few screenshots. Please let me know if I miss anything.
![Screenshot from 2024-05-10 13-31-24](https://github.com/faasm/faasm/assets/167014484/9beaacf2-1529-4a96-9363-1462f7c1c41f)
![WhatsApp Image 2024-05-10 at 13 36 06](https://github.com/faasm/faasm/assets/167014484/55356158-d60a-4b72-a4a3-6e794d36ccf2)
![WhatsApp Image 2024-05-10 at 13 36 06 (1)](https://github.com/faasm/faasm/assets/167014484/0bd0398c-0b7d-4b4e-b99c-a4d24aa9f736)

**Comment by csegarragonz** [comment]
The worker is failing and restarting, could you print the worker logs to see what is going on?

**Comment by HiranmayeeKadali** [comment]
Hii I have used only 2 workers since  I just want to get the results of running the function. But here is the logs of two workers. It says 'Recieved empty requests'.
[logs_worker2.txt](https://github.com/faasm/faasm/files/15275211/logs_worker2.txt)
[logs_worker1_.txt](https://github.com/faasm/faasm/files/15275224/logs_worker1_.txt)

**Comment by csegarragonz** [comment]
Keep in mind that the workers have restarted, so if using `kubectl` you will need to pass the `-p` flag to get the logs of previous pods.

**Comment by HiranmayeeKadali** [comment]
Hii @csegarragonz Here it is
(faasm) sree@sree-VirtualBox:~/faasm$ kubectl logs faasm-worker-866f6cd8f6-drckl -n faasm --previous
Setting up cgroup
CGroup support is off
Setting up namespaces
Network namespace support is off
Deplyoment type: 
[2024-05-09 13:11:36.477] [info] [S3Wrapper.cpp:89] Initialising Faasm S3 setup at minio:9000
[2024-05-09 13:11:36.579] [info] [S3Wrapper.cpp:105] Successfully pinged S3 at minio:9000
[13:11:36] [1] [I] --- HOST ---
[13:11:36] [1] [I] Cgroup mode:          off
[13:11:36] [1] [I] Host type:            default
[13:11:36] [1] [I] Network ns mode:      off
[13:11:36] [1] [I] Max. network ns:      100
[13:11:36] [1] [I] --- MISC ---
[13:11:36] [1] [I] Capture stdout:       on
[13:11:36] [1] [I] Chained call timeout: 300000
[13:11:36] [1] [I] Python preload:       off
[13:11:36] [1] [I] Wasm VM:              wamr
[13:11:36] [1] [I] --- STORAGE ---
[13:11:36] [1] [I] Function dir:         /usr/local/faasm/wasm
[13:11:36] [1] [I] Object file dir:      /usr/local/faasm/object
[13:11:36] [1] [I] Runtime files dir:    /usr/local/faasm/runtime_root
[13:11:36] [1] [I] Shared files dir:     /usr/local/faasm/shared
Testing crash handler backtrace:
/build/faasm/bin/pool_runner(_ZN7faabric4util17setUpCrashHandlerEi+0x76)[0x5bcf0f536546]
/build/faasm/bin/pool_runner(_ZN7faabric6runner11FaabricMain15startBackgroundEv+0x21)[0x5bcf0f4ed501]
/build/faasm/bin/pool_runner(main+0xfe)[0x5bcf0c21a92e]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7c84b9b7bd90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7c84b9b7be40]
/build/faasm/bin/pool_runner(_start+0x25)[0x5bcf0c21a765]
[13:11:36] [1] [I] Installing crash handler
[13:11:36] [1] [I] Installed handler for signal 6
[13:11:36] [1] [I] Installed handler for signal 4
[13:11:36] [1] [I] Installed handler for signal 8
Loading scripts for Redis instance at redis-queue
Loading scripts for Redis instance at redis-state
[13:11:36] [1] [I] Starting state server
[13:11:37] [1] [I] Starting snapshot server
[13:11:37] [1] [I] Starting point-to-point server
[13:11:38] [1] [I] Starting function call server
[13:11:38] [1] [I] Starting endpoint
[13:11:38] [1] [I] Starting HTTP endpoint on 8080, 4 threads
[13:19:32] [62] [W] Worker HTTP handler received empty request!
[13:24:34] [1] [W] Worker HTTP handler received empty request!
[13:24:34] [62] [E] Error reading an HTTP request: bad method
[13:42:10] [63] [W] Worker HTTP handler received empty request!
[13:43:11] [64] [W] Worker HTTP handler received empty request!
[14:26:40] [64] [W] Worker HTTP handler received empty request!
[14:52:39] [63] [W] Worker HTTP handler received empty request!
[15:05:37] [64] [W] Worker HTTP handler received empty request!
[15:05:37] [64] [E] Error reading an HTTP request: bad method
[15:32:31] [1] [W] Worker HTTP handler received empty request!
[15:40:36] [62] [W] Worker HTTP handler received empty request!
[16:26:47] [62] [W] Worker HTTP handler received empty request!
[17:03:17] [63] [W] Worker HTTP handler received empty request!
[18:08:56] [64] [W] Worker HTTP handler received empty request!
[18:47:41] [62] [W] Worker HTTP handler received empty request!
[18:48:07] [62] [W] Worker HTTP handler received empty request!
[18:48:25] [62] [W] Worker HTTP handler received empty request!
[19:44:07] [63] [W] Worker HTTP handler received empty request!
[20:45:39] [64] [W] Worker HTTP handler received empty request!
[20:52:02] [63] [W] Worker HTTP handler received empty request!
[21:12:11] [1] [E] Error reading an HTTP request: bad version
[21:21:22] [62] [E] Error reading an HTTP request: bad version
[21:21:52] [64] [E] Error reading an HTTP request: bad version
[22:11:57] [63] [W] Worker HTTP handler received non-empty request (body: <?=md5("phpunit")?>)
[22:30:34] [62] [W] Worker HTTP handler received empty request!
[22:47:10] [64] [W] Worker HTTP handler received empty request!
[23:02:43] [1] [E] Error reading an HTTP request: Connection reset by peer
[23:02:46] [63] [W] Worker HTTP handler received empty request!
[23:02:46] [1] [E] Error reading an HTTP request: Connection reset by peer
[23:02:49] [63] [W] Worker HTTP handler received empty request!
[23:02:49] [1] [E] Error reading an HTTP request: bad version
[23:09:07] [62] [W] Worker HTTP handler received empty request!
[23:36:30] [63] [E] Error reading an HTTP request: bad version
[00:10:12] [62] [W] Worker HTTP handler received empty request!
[01:08:05] [1] [E] Error reading an HTTP request: bad method
[02:00:46] [62] [W] Worker HTTP handler received empty request!
[03:56:52] [62] [W] Worker HTTP handler received empty request!
[05:32:56] [62] [E] Error reading an HTTP request: bad version
[05:52:27] [1] [E] Error reading an HTTP request: bad version
[06:28:06] [1] [W] Worker HTTP handler received empty request!
[07:02:04] [62] [W] Worker HTTP handler received empty request!
[07:02:06] [63] [W] Worker HTTP handler received empty request!
[07:56:12] [1] [W] Worker HTTP handler received empty request!
[09:31:18] [63] [W] Worker HTTP handler received empty request!
[09:31:18] [62] [E] Error reading an HTTP request: Connection reset by peer
[10:04:20] [64] [W] Worker HTTP handler received empty request!
[10:15:40] [64] [W] Worker HTTP handler received empty request!
[10:37:01] [64] [W] Worker HTTP handler received empty request!
[10:37:26] [1] [W] Worker HTTP handler received empty request!
[10:50:18] [64] [W] Worker HTTP handler received empty request!
[10:50:18] [62] [E] Error reading an HTTP request: Connection reset by peer
[11:33:00] [64] [W] Worker HTTP handler received empty request!
[11:33:37] [68] [I] Chaining nested call demo/pi (ids: 606881 -> 1941095143)
[11:33:37] [68] [I] Chaining nested call demo/pi (ids: 606881 -> 1941095146)
[11:33:37] [68] [I] Chaining nested call demo/pi (ids: 606881 -> 1941095150)
[11:33:37] [68] [I] Chaining nested call demo/pi (ids: 606881 -> 1941095153)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)
Caught stack backtrace:
/build/faasm/bin/pool_runner(_ZN7faabric4util11handleCrashEi+0x21)[0x5bcf0f536441]
/build/faasm/bin/pool_runner(_Z12crashHandleri+0x9)[0x5bcf0f536409]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7c84b9b94520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7c84b9be89fc]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7c84b9b94476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7c84b9b7a7f3]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2b9e)[0x7c84b9e3fb9e]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae20c)[0x7c84b9e4b20c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae277)[0x7c84b9e4b277]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae4d8)[0x7c84b9e4b4d8]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa54cd)[0x7c84b9e424cd]
/build/faasm/bin/pool_runner(_ZN7faabric5state21InMemoryStateKeyValue22pullAppendedFromRemoteEPhml+0x167)[0x5bcf0f50c287]
/build/faasm/bin/pool_runner(_ZN7faabric5state13StateKeyValue11getAppendedEPhml+0x45)[0x5bcf0f50f275]
/build/faasm/bin/pool_runner(+0x4036122)[0x5bcf0c266122]
[0x4197649f]
[11:38:38] [68] [E] Destructing scheduler without shutting down first
pure virtual method called
terminate called recursively

**Comment by HiranmayeeKadali** [comment]
Hii @csegarragonz Can you let me know if there is any problem?
