### ISSUE TITLE
Python: functions not working and it's impossible to run older tagged versions

### ISSUE THREAD

**Issue by bsdinis** [faasm/faasm#880]
Hi.
I've been trying to run python functions in FAASM, running into some issues.

# 1. Following the [Python Documentation for FAASM](https://faasm.readthedocs.io/en/stable/source/python.html)

```
export PYTHON_CODEGEN=on
faasmctl deploy.compose
faasmctl cli.python

inv cpython.func # works until here
inv cpython.upload # returns `Response(500):` with no further explanation

inv func.uploadpy hello # this still works
inv --debug func.invoke python hello # this gets caught in a retry loop
```

The retry loop above looks something like this:
```
...
urllib3.connectionpool.connectionpool._new_conn: Starting new HTTP connection (1): planner:8080
urllib3.connectionpool.connectionpool._make_request: http://planner:8080 "POST / HTTP/11" 200 16
urllib3.connectionpool.connectionpool._new_conn: Starting new HTTP connection (1): planner:8080
urllib3.connectionpool.connectionpool._make_request: http://planner:8080 "POST / HTTP/11" 500 29
urllib3.connectionpool.connectionpool._new_conn: Starting new HTTP connection (1): planner:8080
urllib3.connectionpool.connectionpool._make_request: http://planner:8080 "POST / HTTP/11" 500 29
urllib3.connectionpool.connectionpool._new_conn: Starting new HTTP connection (1): planner:8080
urllib3.connectionpool.connectionpool._make_request: http://planner:8080 "POST / HTTP/11" 500 29
urllib3.connectionpool.connectionpool._new_conn: Starting new HTTP connection (1): planner:8080
urllib3.connectionpool.connectionpool._make_request: http://planner:8080 "POST / HTTP/11" 500 29
...
``` 

Naturally, wasn't really expecting the function invocation to work given that uploading the compiled CPython failed, but it's interesting that this is the failure model.

# 2. Looking over existing Github Issues

Found this comment in #795 from roughly a year ago: https://github.com/faasm/faasm/issues/795#issuecomment-2104217292
> python support is kinda broken as of now so i would not expect it to work (just yet!)

# 3. Trying to run older versions

As python support broke at some point in time, I tried to run older versions of FAASM (going through all tagged versions from `v0.15.0` to `main`). All of them except `main` and `v0.27.0` have missing container images.

Example given below with `v0.26.0`:
```
bsdinis@machine:~/dev/faasm (:4ae2e6d|…1)
% git log
bsdinis@machine:~/dev/faasm (:4ae2e6d|…1)
% git describe --exact-match --tags
v0.26.0                                                                                                  bsdinis@machine:~/dev/faasm (:4ae2e6d|…1)
% git rev-parse @
4ae2e6d340f3099cbcabeae827aa6385338bbc89
bsdinis@machine:~/dev/faasm (:4ae2e6d|…1)
% git submodule update --init --recursive
bsdinis@machine:~/dev/faasm (:4ae2e6d|…1)
% faasmctl deploy.compose
WARN[0000] /home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/faasmctl/.config/faasm-source/0.26.0/docker-compose.yml: `version` is obsolete                                                                         [+] Running 6/6
 ✘ upload Error      context canceled                                                               0.3s
 ✘ redis-state Error context canceled                                                               0.3s
 ✘ worker Error      context canceled                                                               0.3s
 ✘ redis-queue Error context canceled                                                               0.3s
 ✘ minio Error       manifest for faasm.azurecr.io/minio:0.26.0 not found: manifest...              0.3s
 ✘ planner Error     context canceled                                                               0.3s
Error response from daemon: manifest for faasm.azurecr.io/minio:0.26.0 not found: manifest unknown: manifest tagged by "0.26.0" is not found
Traceback (most recent call last):                                                                         File "/home/bsdinis/dev/faasm/venv-bm/bin/faasmctl", line 8, in <module>
    sys.exit(main())
             ^^^^^^                                                                                        File "/home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/faasmctl/main.py", line 14, in main
    program.run()
  File "/home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/invoke/program.py", line 398, in run
    self.execute()                                                                                         File "/home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    File "/home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/faasmctl/tasks/deploy.py", line 50, in compose
    return deploy_compose_cluster(faasm_checkout, workers, mount_source, ini_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bsdinis/dev/faasm/venv-bm/lib/python3.12/site-packages/faasmctl/util/compose.py", line 188, in deploy_compose_cluster                                                                                                run(cmd, shell=True, check=True, cwd=faasm_checkout, env=env)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker compose up -d --scale worker=2  worker' returned non-zero exit status 18.
```

# 4. Questions

1. Is there a known version where Python was working?
2. Is there a way to rebuild the images (even if locally) so that it becomes possible to run this known version?

Appreciate the work and the help! Let me know if you need more context at all :-)

**Comment by csegarragonz** [comment]
Hi @bsdinis , thanks for using Faasm and for the detailed write-up!

Let me start from the end:

> Is there a way to rebuild the images (even if locally) so that it becomes possible to run this known version?

Yes, just check-out to the tag and run: `inv docker.build-all`.

As you have already noticed, the way Faasm supported Python was by cross-compiling CPython to WASM, and feeding the actual function's bytecode to a home-made entrypoint. To support any kind of complex feature, we also implemented support for shared library loading (aka `dlopen` and friends).

The latter only worked with WAVM as WASM runtime, which unfortunately is long unmaintained. On the other hand, other WASM feautres like threads have only been upstreamed to LLVM versions that can't even compile WAVM. As a consequence, Python support fell into a no-man's land, and it isn't needed for our current research, so hence why it rot.

> Is there a way to rebuild the images (even if locally) so that it becomes possible to run this known version?

IIRC python support broke during the last LLVM toolchain upgrade: https://github.com/faasm/faasm/pull/840
You may get lucky by just travelling back in time, but I don't expect anything overly complex to work.

The most interesting path forward would be implementing `dlopen` and friends for WAMR, and resurrecting Python support altogether. There is now a much greater push in the whole WASM environment to execute Python, so I'd expect it to be much more straightforward than when Simon did it first five years ago :-D (e.g. see https://github.com/bytecodealliance/componentize-py)

Hope this helps!
