### ISSUE TITLE
Destructing Executor without shutting down first

### ISSUE THREAD

**Issue by aminb7** [faasm/faasm#894]
Hello,
I've tried to deploy Faasm on Kubernetes. As I wanted to send synchronous requests to Faasm, I used Faasm v0.8.12. I've overwritten an environment variable to change the maximum number of concurrent requests and not to use the number of cores.

I sent 2 requests to run a simple hello world function. I observed some amount of memory being allocated (4GB - 1 page) which was never released after allocation:

![Screenshot 2024-11-12 at 4 27 42 PM](https://github.com/user-attachments/assets/d498c637-5b4f-4269-ad1c-b12a3dc9e453)

The first request failed and triggered growing memory (based on the Faasm logs below) and the second one was successful. Also, it seems the destruction of Executor has failed (based on the Faasm logs below) which I thought might be relevant to not releasing memory (4GB - 1 page of memory).

```
[00:52:14] [95] [E] Growing memory would exceed max of 65535 pages (current 65518, requested 65570)
[00:52:14] [95] [E] Destructing Executor 10.233.105.177_1097698848 without shutting down first
```

I would appreciate any insight into what could be the reason or if I missed anything while setting up the system.

Thanks for your help!

**Comment by csegarragonz** [comment]
Hey @aminb7, many thanks for using Faasm!

What do you mean by "synchronous requests"?
Note that `v0.8.2` is a rather old version.
What prevents you from using the latest version?

Also, are you using `faasmctl` to deploy the cluster, cross-compile and upload functions?
Could you provide more details on the steps you ran?

Regarding the memory usage, Faasm uses _virtual_ memory to enforce WASM sandbox bound checks.
(In fact, this is what WAVM and WAMR do, so Faasm does not do anything here).

**Comment by csegarragonz** [comment]
To measure latency, our current set-up should be OK. Even though we poll for the response, we can extract the actual execution time from the message metadata, see this method [here](https://github.com/faasm/faasmctl/blob/main/faasmctl/util/results.py#L1-L24).

To measure throughput, I agree, the current set-up may not give ideal results, depending on how short lived your functions are. I see various options:
1. For a throughput micro-benchmark, you could spin up a local CLI container, and execute functions directly there. See for example how `inv run` (from inside the CLI container) [works](https://github.com/faasm/faasm/blob/main/tasks/run.py#L22-L28) by calling the [`func_runner.cpp`](https://github.com/faasm/faasm/blob/main/src/runner/func_runner.cpp).
2. For a larger macro-benchmark, I would be curious to see what are the bottlenecks even with the current planner design. Particularly depending on the workload you are running. As long as you are setting the `OVERRIDE_CPU_COUNT` variable high enough, I wonder what will start breaking up first. Other than the Python CLI, I would expect the `planner` to be able to maintain some decent throughput.

All in all, I would strongly discourage you from: (1) using such an old version of Faasm, (2) deploying on K8s manually, and (3) not using our cross-compilation tool-chain. Each of the previous is not officially maintained, and can be a source of errors in themselves. Let alone combined.

I would also encourage you to, while exploring Faasm, consider using a [development](https://github.com/faasm/faasm/blob/main/docs/source/development.md) cluster on `docker compose`. As long as your are building the binaries in `Release` mode, that should give _good enough_ results for a preliminary study. The only caveat is that you need a somewhat beefy server to run all the cluster in it, but nothing too crazy.

**Comment by csegarragonz** [comment]
The issue you are facing is due to different build directories not being mounted correctly. It is probably a consequence of using an old tag that may not contain the fixes to, for example, the issue you mention.

What are you exactly trying to measure?

If you are measuring latency, would not the method suggested above work in a "serverless" fashion? To all effects, you are just sending a request and getting a result in return, and the execution time is the time spent actually executing the function.

The only thing we have removed is direct worker access, so we must now do a hop through the planner. This will have an impact on throughput, but, as I said, I'm curious to know what will be the bottleneck.

**Comment by aminb7** [comment]
Thanks for your reply.
I want to measure end-to-end response time and throughput of Faasm deployed on K8s.

Can I still use `inv run` which calls [func_runner](https://github.com/faasm/faasm/blob/main/src/runner/func_runner.cpp) to run the function in the Faasm worker deployed on a k8s cluster?

**Comment by csegarragonz** [comment]
For end-to-end response time, you can use the method I described above with the latest Faasm version.

For throughput, you can use the `func_runner`. The `func_runner` _does not_ execute the function in the worker in the k8s cluster. Instead, it executes it locally, in the CLI container. You could modify the `func_runner` to measure throughput of one Faasm instance. (Note that the CLI container is just like a worker container, but with a few blows and whistles to be able to develop.)

**Comment by aminb7** [comment]
Thanks for your help.

I am using Faasm deployed on K8s using `faasmctl`. I configured `OVERRIDE_CPU_COUNT` to `64` based on the concurrency and the duration of functions I am executing. I send requests to Faasm the same way `faasmctl invoke` does (sendin a `EXECUTE_BATCH` request and then polling for result by sending `EXECUTE_BATCH_STATUS` requests).

I am facing an issue (`Not enough free slots`) at some point during the run.
The planner begins failing all requests due to a lack of available slots.
It seems that slots are not being released for some of the requests, eventually leading to a state where all slots are full and never released again. I also observed this behavior while monitoring the planner using faasmctl monitor.planner.

This is the planner logs during the run:

```

[pod/planner/planner] [07:35:51] [39] [I] Planner removing app 775695 from in-flight
...
[pod/planner/planner] [07:35:51] [39] [I] Planner removing app 137894 from in-flight
[pod/planner/planner] [07:35:52] [40] [I] Planner removing app 260111 from in-flight
[pod/planner/planner] [07:35:52] [41] [I] Planner removing app 698631 from in-flight
[pod/planner/planner] [07:35:52] [38] [I] Planner removing app 478698 from in-flight
[pod/planner/planner] [07:35:52] [39] [I] Planner removing app 400172 from in-flight
[pod/planner/planner] [07:35:53] [40] [I] Planner removing app 975047 from in-flight
[pod/planner/planner] [07:37:04] [51] [E] Not enough free slots to schedule app: 240227 (requested: 1)
[pod/planner/planner] [07:37:04] [52] [E] Not enough free slots to schedule app: 447997 (requested: 1)
[pod/planner/planner] [07:37:05] [7] [E] Not enough free slots to schedule app: 282169 (requested: 1)
[pod/planner/planner] [07:37:05] [51] [E] Not enough free slots to schedule app: 677081 (requested: 1)
[pod/planner/planner] [07:37:06] [7] [E] Not enough free slots to schedule app: 635321 (requested: 1)
[pod/planner/planner] [07:37:07] [51] [E] Not enough free slots to schedule app: 255971 (requested: 1)
[pod/planner/planner] [07:37:07] [52] [E] Not enough free slots to schedule app: 418533 (requested: 1)
[pod/planner/planner] [07:37:07] [7] [E] Not enough free slots to schedule app: 518508 (requested: 1)
[pod/planner/planner] [07:37:07] [7] [E] Not enough free slots to schedule app: 627855 (requested: 1)
[pod/planner/planner] [07:37:07] [51] [E] Not enough free slots to schedule app: 242242 (requested: 1)
[pod/planner/planner] [07:37:07] [52] [E] Not enough free slots to schedule app: 804699 (requested: 1)
...
[pod/planner/planner] [07:37:07] [52] [E] Not enough free slots to schedule app: 328153 (requested: 1)

```

I would appreciate it if you could share insights on how bookkeeping works in the planner and whether there is anything I might be missing.

Thank you!

**Comment by csegarragonz** [comment]
My best hint would be to re-run the planner with `LOG_LEVEL=debug`. This may require re-building the targets in `Debug` mode with something like:

```
faasmctl cli.faasm
inv dev.tools --build Debug
exit
faasmctl restart -s planner -s worker
```

The `Debug` logs should be more revealing.

**Comment by aminb7** [comment]
Thanks. I'll try that.

**Comment by aminb7** [comment]
I tried to use Debug mode. Seems it is for docker compose deployment based on the error message. Is there any way to run planner in debug mode on K8s?

Error message:
```
$ faasmctl cli.faasm
Traceback (most recent call last):
  File "/mnt/amin/faasm/venv-bm/bin/faasmctl", line 8, in <module>
    sys.exit(main())
  File "/mnt/amin/faasm/venv-bm/lib/python3.10/site-packages/faasmctl/main.py", line 14, in main
    program.run()
  File "/mnt/amin/faasm/venv-bm/lib/python3.10/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/mnt/amin/faasm/venv-bm/lib/python3.10/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/mnt/amin/faasm/venv-bm/lib/python3.10/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
  File "/mnt/amin/faasm/venv-bm/lib/python3.10/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
  File "/mnt/amin/faasm/venv-bm/lib/python3.10/site-packages/faasmctl/tasks/cli.py", line 118, in faasm
    do_run_cmd("faasm-cli", cmd, cp_in, cp_out, env, ini_file)
  File "/mnt/amin/faasm/venv-bm/lib/python3.10/site-packages/faasmctl/tasks/cli.py", line 83, in do_run_cmd
    raise RuntimeError("Can't call cli.faasm on a `k8s` cluster!")
RuntimeError: Can't call cli.faasm on a `k8s` cluster!
```

**Comment by csegarragonz** [comment]
To run on Kubernetes we directly use a docker image tag. This images are built as part of our release process, and default to a `Release` build.

Using Kubernetes in debug mode would involve baking a new image tag where you change the build command to use `Debug` and updating the `k8s` deployment files to use this new tag.

Is there any reason why you cannot use docker compose?
